---------------------------------
[2025-05-19 21:46:33][INFO][200]:La conexion [dbconn_standard] esta desabilitada en el archivo .config
---------------------------------
[2025-05-19 21:46:33][INFO][200]:Iniciando ...
---------------------------------
[2025-05-19 21:46:33][INFO][200]:[INFO] Reading from rtsp://100.108.97.81:8554/cam1
---------------------------------
[2025-05-19 21:46:34][INFO][200]:Starting multithreading
---------------------------------
[2025-05-19 21:46:34][INFO][200]:[INFO] Showing video...
---------------------------------
[2025-05-19 21:46:34][EXCEPTION][500]:PYTHON-EXCEPTION:

>>>>>>>>>>>>>>>[TRACEBACK]<<<<<<<<<<<<<<<

  File "/Users/l03542515/Documents/pinos-analytics-cv/src/IOT-Agent/main.py", line 10, in <module>
    ProjectDirector.go( sys.argv )
  File "/Users/l03542515/Documents/pinos-analytics-cv/src/IOT-Agent/System/Director/ProjectDirector.py", line 127, in go
    ProjectDirector().setFlux( argv )
  File "/Users/l03542515/Documents/pinos-analytics-cv/src/IOT-Agent/System/Director/ProjectDirector.py", line 107, in setFlux
    self.__play(
  File "/Users/l03542515/Documents/pinos-analytics-cv/src/IOT-Agent/System/Director/ProjectDirector.py", line 55, in __play
    detector = MovementDetector(
  File "/Users/l03542515/Documents/pinos-analytics-cv/src/IOT-Agent/System/App/MovementDetector/MovementDetector.py", line 94, in __init__
    self.recorder = RTSPRecorder(camera=camera, folder=folder, codec=codec, width=width, height=height, fps=src_fps, verbose=verbose, visualize=visualize)
  File "/Users/l03542515/Documents/pinos-analytics-cv/src/IOT-Agent/System/App/RTSPRecorder/RTSPRecorder.py", line 46, in __init__
    self.uploader = Uploader()

>>>>>>>>>>>>>>[ERROR_DESC]<<<<<<<<<<<<<<<

  [TypeError]:__init__() missing 2 required positional arguments: 'account_url' and 'sas_token'

>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<

